---
Name: graphql-forms
---
SilverStripe\Core\Injector\Injector:
  UncleCheese\GraphQLForms\FormFactoryRegistry:
    properties:
      factories:
        default: '%$UncleCheese\GraphQLForms\DefaultFormFactory'
---
Only:
  moduleexists: 'silverstripe/userforms'
---
SilverStripe\Core\Injector\Injector:
  UncleCheese\GraphQLForms\FormFactoryRegistry:
    properties:
      factories:
        userforms: '%$UncleCheese\GraphQLForms\UserDefinedFormFactory'

